# Generated by Django 4.2.4 on 2023-09-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('N', 'Normal'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='N', max_length=6)),
                ('price', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
