# Generated by Django 4.2.4 on 2023-09-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_free_normal',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
