# Generated by Django 4.2.4 on 2023-09-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_baseuser_is_admin_baseuser_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='customer_status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'GOLD')], default='Normal', max_length=6, null=True),
        ),
    ]
