# Generated by Django 4.2.4 on 2023-09-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_baseuser_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='customer_status',
            field=models.CharField(choices=[('N', 'Normal'), ('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='N', max_length=1),
        ),
    ]
