# Generated by Django 4.2.4 on 2023-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_date', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('weekday', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('market', models.CharField(max_length=255)),
            ],
        ),
    ]
