# Generated by Django 4.2.4 on 2023-09-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartMoneyInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_date', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('market', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SmartMoneyOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_date', models.CharField(max_length=255)),
                ('ticker', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('market', models.CharField(max_length=255)),
            ],
        ),
    ]
